name: Build Flutter Application

on: [push, pull_request]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.flutter-action.outputs.CACHE-KEY }}
      cache-path: ${{ steps.flutter-action.outputs.CACHE-PATH }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true

  build-windows:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache-key: ${{ needs.setup.outputs.cache-key }}
          cache-path: ${{ needs.setup.outputs.cache-path }}

      - run: flutter build windows

  build-linux:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache-key: ${{ needs.setup.outputs.cache-key }}
          cache-path: ${{ needs.setup.outputs.cache-path }}

      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux

  build-macos:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache-key: ${{ needs.setup.outputs.cache-key }}
          cache-path: ${{ needs.setup.outputs.cache-path }}

      - run: flutter build macos
